------------
mpifort -c  -O3 -assume byterecl -g -traceback -ip -module /home/xychen/ADC-WW3-Coupling-Dev/SrcCode/WW3/model/mod -convert big_endian -I/usr/share/Modules/software/CentOS-7/netcdf-Fortran/4.4.0_intel-18.0.0/include -I/home/xychen/ADC-WW3-Coupling-Dev/SrcCode/WW3/model/ftn/PDLIB -I/projects/ees/dhs-crc/xychen/ESMFlib_openmpi_xyc/mod/modg/Linux.intel.64.openmpi.default -I/projects/ees/dhs-crc/xychen/ESMFlib_openmpi_xyc/include -I/usr/share/Modules/software/CentOS-7/netcdf-Fortran/4.4.0_intel-18.0.0/include 
------------
------------
------------
